"""Every SWE-bench table in the paper, rebuilt from the stored result files.

    py -3 scripts/research/paper_tables.py --swe <swebench dir> [--repos <clones>] [--out tables.md]

Reads the harness outputs (`swebench_localize.py` jsonl), the instance subsets
under `<swe>/devset/`, and the function-gold caches (`func-gold-*.json`, built
by `func_eval.py --gold-cache`; computed from the clones when missing). Runs that
are not on disk are skipped with a note, so the script works at any point of
the project. Published numbers are constants below, each with its source.
"""
import argparse
import json
import os
import statistics
import sys

sys.path.insert(0, os.path.dirname(__file__))
from eval_loc import acc  # noqa: E402
from func_eval import boot_ci, load_gold, same  # noqa: E402

# (label, results file, list key) per benchmark; first existing file wins per label.
RUNS = {
    "lite": [
        ("engine v1.2.0", "results-final-test.jsonl", "loc_files"),
        ("engine v1.3.0", "lite-v130-all.jsonl", "loc_files"),
        ("engine v1.4.0", "lite-v140-all.jsonl", "loc_files"),
    ],
    "verified": [
        ("engine v1.2.0", "results-verified-v120.jsonl", "loc_files"),
        ("engine v1.3.0", "verified-v130-all.jsonl", "loc_files"),
        ("engine v1.4.0", "verified-v140-all.jsonl", "loc_files"),
    ],
}
SUBSETS = {
    "Lite strict holdout": ("lite", "devset/lite-holdout-ids.json"),
    "Lite, LocAgent subset": ("lite", "devset/locagent-274.json"),
    "Verified, all": ("verified", None),
    "Verified, not in Lite": ("verified", "devset/verified-not-lite.json"),
}
ABLATION = [  # Lite strict holdout, v1.2.0 engine with one component switched off (NM_ABLATE build)
    ("nothing removed", "results-final-test.jsonl", "loc_files"),
    ("report hygiene + code tokens (C11)", "abl-hyg-all.jsonl", "loc_files"),
    ("definition-level ranking (C12)", "abl-chunk-all.jsonl", "loc_files"),
    ("localisation list (packet order only)", "results-final-test.jsonl", "ours_files"),
]
# LocAgent (arXiv 2503.09089) Table 4, SWE-bench Lite, their 274-instance subset.
PUBLISHED_FILE = [
    ("BM25 †", "–", 0.3869, 0.5182, 0.6168),
    ("Jina-Code-v2 †", "–", 0.4343, 0.7117, 0.8029),
    ("CodeRankEmbed †", "–", 0.5255, 0.7774, 0.8467),
    ("Agentless + GPT-4o †", "✓", 0.6715, 0.7445, 0.7445),
    ("Agentless + Claude-3.5 †", "✓", 0.7263, 0.7920, 0.7956),
    ("LocAgent + Qwen2.5-7B (ft) †", "✓", 0.7080, 0.8467, 0.8832),
    ("LocAgent + Claude-3.5 †", "✓", 0.7774, 0.9197, 0.9416),
]
PUBLISHED_FUNC = [  # function level Acc@5 / Acc@10, same table
    ("BM25 †", 0.3175, 0.3686),
    ("CodeRankEmbed †", 0.5182, 0.5876),
    ("Agentless + Claude-3.5 †", 0.5876, None),
    ("LocAgent + Claude-3.5 †", 0.7336, 0.7737),
]


def load(path):
    out = {}
    for line in open(path, encoding="utf-8"):
        if line.strip():
            r = json.loads(line)
            if "error" not in r:
                out[r["instance_id"]] = r
    return out


def ids_of(swe, subset, rows):
    if subset is None:
        return [r["instance_id"] for r in rows]
    return [r["instance_id"] for r in json.load(open(os.path.join(swe, subset), encoding="utf-8"))]


def fmt(vals, ci):
    m = sum(vals) / len(vals)
    if not ci:
        return f"{m:.3f}"
    lo, hi = boot_ci(vals)
    return f"{m:.3f} [{lo:.2f},{hi:.2f}]"


def file_row(res, ids, key, ks=(1, 3, 5, 10), ci=True):
    """Acc@k over `ids`; an instance the run lost (checkout error) counts as a miss."""
    cells = []
    for k in ks:
        if key.startswith("bm25"):
            vals = [res[i].get(f"bm25_hit@{k}", 0) if i in res else 0 for i in ids]
        else:
            vals = [acc(res[i].get(key) or [], res[i]["gold"], k) if i in res else 0 for i in ids]
        cells.append(fmt(vals, ci and k in (1, 3, 5)))
    return cells


def func_row(res, ids, golds, key="definitions", ks=(1, 5, 10)):
    have = [i for i in ids if golds.get(i)]
    cells = []
    for k in ks:
        vals = []
        for i in have:
            preds = [(d["path"], d["name"]) for d in (res.get(i, {}).get(key) or [])][:k]
            vals.append(int(all(any(same(p, g) for p in preds) for g in golds[i])))
        cells.append(fmt(vals, k == 5))
    return len(have), cells


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--swe", required=True)
    ap.add_argument("--repos", default="")
    ap.add_argument("--out", default="")
    args = ap.parse_args()
    swe = args.swe
    repos = args.repos or os.path.join(swe, "repos")
    data = {"lite": json.load(open(os.path.join(swe, "lite.json"), encoding="utf-8")),
            "verified": json.load(open(os.path.join(swe, "verified.json"), encoding="utf-8"))}
    rows_by = {b: {r["instance_id"]: r for r in d} for b, d in data.items()}
    lines = ["# Paper tables (generated by scripts/research/paper_tables.py)", ""]

    runs = {}
    for bench, lst in RUNS.items():
        for label, f, key in lst:
            p = os.path.join(swe, f)
            if os.path.exists(p):
                runs[(bench, label)] = (load(p), key)
            else:
                lines.append(f"_skipped: {bench} {label} ({f} not found)_")
    lines.append("")

    lines += ["## File level (all gold files in the top k; 95% bootstrap CI)", "",
              "| set | n | method | Acc@1 | Acc@3 | Acc@5 | Acc@10 |", "|---|---|---|---|---|---|---|"]
    for name, (bench, subset) in SUBSETS.items():
        ids = ids_of(swe, subset, data[bench])
        # BM25 from the run that scored it on the most instances (an older run
        # may have lost a few to checkout errors).
        cands = [runs[k][0] for k in runs if k[0] == bench]
        bm_src = max(cands, key=lambda res: sum("bm25_hit@1" in r for r in res.values()), default=None)
        if bm_src is not None:
            lines.append(f"| {name} | {len(ids)} | BM25 | " + " | ".join(file_row(bm_src, ids, "bm25")) + " |")
        for (b, label), (res, key) in runs.items():
            if b == bench:
                lines.append(f"| {name} | {len(ids)} | {label} | " + " | ".join(file_row(res, ids, key)) + " |")
    lines += ["", "Published (LocAgent Table 4, Lite 274): " + "; ".join(
        f"{n} {a1:.3f}/{a3:.3f}/{a5:.3f}" for n, _, a1, a3, a5 in PUBLISHED_FILE), ""]

    lines += ["## Function level (every edited function in the top k)", "",
              "| set | n with function gold | method | Acc@1 | Acc@5 | Acc@10 |", "|---|---|---|---|---|---|"]
    gold_cache = {"lite": os.path.join(swe, "func-gold-lite.json"),
                  "verified": os.path.join(swe, "func-gold-verified.json")}
    golds = {}
    for bench in data:
        all_ids = [r["instance_id"] for r in data[bench]]
        golds[bench] = load_gold(rows_by[bench], all_ids, repos, gold_cache[bench])
    for name, (bench, subset) in SUBSETS.items():
        ids = ids_of(swe, subset, data[bench])
        for (b, label), (res, _) in runs.items():
            if b == bench and any("definitions" in r for r in res.values()):
                n, cells = func_row(res, ids, golds[bench])
                lines.append(f"| {name} | {n} | {label} | " + " | ".join(cells) + " |")
    lines += ["", "Published function Acc@5/@10 (LocAgent Table 4): " + "; ".join(
        f"{n} {a5:.3f}/{a10:.3f}" if a10 else f"{n} {a5:.3f}" for n, a5, a10 in PUBLISHED_FUNC), ""]

    lines += ["## Ablation (Lite strict holdout, 276)", "",
              "| removed | Acc@1 | Acc@3 | Acc@5 | Acc@10 |", "|---|---|---|---|---|"]
    ids = ids_of(swe, "devset/lite-holdout-ids.json", data["lite"])
    for label, f, key in ABLATION:
        p = os.path.join(swe, f)
        if os.path.exists(p):
            lines.append(f"| {label} | " + " | ".join(file_row(load(p), ids, key, ci=False)) + " |")
    lines.append("")

    lines += ["## Cost per issue (cold index included, laptop CPU)", "",
              "| run | n | latency p50 | p90 | packet tokens p50 |", "|---|---|---|---|---|"]
    for (bench, label), (res, _) in runs.items():
        lat = sorted(r["ours_latency_ms"] for r in res.values() if r.get("ours_latency_ms") is not None)
        tok = sorted(r["ours_tokens"] for r in res.values() if r.get("ours_tokens") is not None)
        if lat:
            lines.append(f"| {bench} {label} | {len(lat)} | {statistics.median(lat) / 1000:.1f} s | "
                         f"{lat[int(0.9 * (len(lat) - 1))] / 1000:.1f} s | {int(statistics.median(tok))} |")
    text = "\n".join(lines) + "\n"
    if args.out:
        open(args.out, "w", encoding="utf-8", newline="\n").write(text)
    print(text)


if __name__ == "__main__":
    main()
